<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NRABHQU" failures="1" tests="1" name="TestSelling" time="21.614" errors="0" timestamp="2022-07-05T08:38:30 IST">
  <testcase classname="com.qa.testLayer.SellingTest" name="verifySellShare" time="14.06">
    <failure type="java.lang.AssertionError" message="expected [Order Created successfully] but found [Order Created sucessfully]">
      <![CDATA[java.lang.AssertionError: expected [Order Created successfully] but found [Order Created sucessfully]
at com.qa.testLayer.SellingTest.verifySellShare(SellingTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifySellShare -->
</testsuite> <!-- TestSelling -->
